version: '3.1'
services:
  stats-service:
    build: statistics/stats-server
    image: stats-service
    container_name: stats-service
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - STATS_SERVER_URL=http://stats-service:9090
      - SERVER_PORT=9090
    depends_on:
      - stats-db

  stats-db:
    image: postgres:14-alpine
    restart: always
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  ewm-service:
    image: amazoncorretto:11-alpine-jdk
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://stats-service:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-service
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm

  ewm-db:
    image: postgres:14-alpine
    restart: always
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres